036_stacking_ensemble## RealMLP on Predicting Heart Disease

**Score**
- PB: 0.95389
- CV: 0.955689

**Note**
- submit only RealMLP

### Package import

In [1]:
!pip install pytabkit -q

from pathlib import Path
import json
import zipfile
import subprocess

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import warnings
from sklearn.metrics import roc_auc_score
from pytabkit import RealMLP_TD_Classifier
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings('ignore')

sns.set_theme(style="whitegrid")

# ---- Config ----
COMP_SLUG = "playground-series-s6e2"
KAGGLE_COMP_DIR = Path("/kaggle/input/competitions/playground-series-s6e2")
KAGGLE_EXT_PATH = Path("/kaggle/input/datasets/neurocipher/heartdisease/Heart_Disease_Prediction.csv")

LOCAL_DATA_DIR = Path("data/raw")
LOCAL_DATA_DIR.mkdir(parents=True, exist_ok=True)

NEED_FILES = ["train.csv", "test.csv", "sample_submission.csv"]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.0/364.0 kB 6.8 MB/s eta 0:00:00

In [2]:
def run(cmd: list[str]) -> None:
    p = subprocess.run(cmd, capture_output=True, text=True)
    p.check_returncode()


def ensure_kaggle_cli() -> None:
    try:
        pass
    except Exception:
        subprocess.check_call(["pip", "-q", "install", "kaggle"])


def ensure_kaggle_json_interactive_colab(dst: Path = Path("/content/kaggle.json")) -> Path:
    """
    In Colab: open upload dialog if /content/kaggle.json is missing.
    In non-Colab: just require the file to exist.
    """
    if dst.exists():
        print("Found:", dst)
        return dst

    try:
        from google.colab import files  # type: ignore
    except Exception:
        raise FileNotFoundError(
            f"{dst} not found. Please place kaggle.json at {dst} (Colab) "
            "or provide credentials another way."
        )

    print("Upload your kaggle.json (Kaggle -> Account -> API -> Create New Token)")
    uploaded = files.upload()
    cand = None
    if "kaggle.json" in uploaded:
        cand = "kaggle.json"
    else:
        for name in uploaded.keys():
            if name.endswith(".json"):
                cand = name
                break
    if cand is None:
        raise FileNotFoundError("Upload failed: no .json file received.")

    Path(cand).rename(dst)
    print("Saved to:", dst)
    return dst


def install_kaggle_json(src: Path) -> None:
    """
    Copy /content/kaggle.json -> ~/.kaggle/kaggle.json (chmod 600)
    """
    if not src.exists():
        raise FileNotFoundError(f"{src} not found.")

    dst_dir = Path.home() / ".kaggle"
    dst_dir.mkdir(parents=True, exist_ok=True)
    dst = dst_dir / "kaggle.json"

    dst.write_bytes(src.read_bytes())
    try:
        dst.chmod(0o600)
    except Exception:
        pass

    cfg = json.loads(dst.read_text())
    if "username" not in cfg or "key" not in cfg:
        raise ValueError("kaggle.json is missing 'username' or 'key'.")
    print(f"Installed kaggle.json for user: {cfg['username']}")


def local_data_ready(data_dir: Path) -> bool:
    return all((data_dir / f).exists() for f in NEED_FILES)


def download_competition_to(data_dir: Path) -> None:
    """
    Download competition zip(s) and extract into data_dir.
    Assumes kaggle CLI + credentials are ready.
    """
    run(["kaggle", "config", "view"])
    run(["kaggle", "competitions", "download", "-c", COMP_SLUG, "-p", str(data_dir), "--force"])

    zips = list(data_dir.glob("*.zip"))
    if not zips:
        raise FileNotFoundError(f"No zip found in {data_dir} after download.")

    for zp in zips:
        with zipfile.ZipFile(zp, "r") as zf:
            zf.extractall(data_dir)
        print("Unzipped:", zp.name)

    if not local_data_ready(data_dir):
        missing = [f for f in NEED_FILES if not (data_dir / f).exists()]
        raise FileNotFoundError(f"Download/unzip finished but missing: {missing}")

In [3]:
if KAGGLE_COMP_DIR.exists():
    DATA_SRC = "kaggle"
    data_dir = KAGGLE_COMP_DIR
    print("Using Kaggle mounted competition data:", data_dir)
else:
    DATA_SRC = "local"
    data_dir = LOCAL_DATA_DIR
    if local_data_ready(data_dir):
        print("Using local data (already present):", data_dir)
    else:
        print("Local data missing -> download using kaggle.json")
        ensure_kaggle_cli()
        kaggle_json_src = ensure_kaggle_json_interactive_colab(Path("/content/kaggle.json"))
        install_kaggle_json(kaggle_json_src)
        download_competition_to(data_dir)
        print("Download complete -> using local data:", data_dir)


# ---- Load ----
train = pd.read_csv(data_dir / "train.csv")
test  = pd.read_csv(data_dir / "test.csv")
sub   = pd.read_csv(data_dir / "sample_submission.csv")

# external dataset: only available if mounted on Kaggle; optional
original = pd.read_csv(KAGGLE_EXT_PATH) if KAGGLE_EXT_PATH.exists() else None

print("train:", train.shape, "test:", test.shape, "sub:", sub.shape, "original:", None if original is None else original.shape)
print("DATA_SRC:", DATA_SRC)

# External data loading
train_comp = train.copy()

# Encode target with LabelEncoder if not numeric
if not pd.api.types.is_numeric_dtype(train_comp["Heart Disease"]):
    le = LabelEncoder()
    train_comp["Heart Disease"] = le.fit_transform(train_comp["Heart Disease"])
    if original is not None and "Heart Disease" in original.columns:
        original["Heart Disease"] = le.transform(original["Heart Disease"])

# Align external columns to train schema
if original is not None:
    if "Heart Disease" not in original.columns:
        raise ValueError("External dataset missing target column: Heart Disease")

    original_aligned = original.copy()
    # add missing columns
    for col in train_comp.columns:
        if col not in original_aligned.columns:
            original_aligned[col] = np.nan

    # ensure id exists
    if "id" not in original_aligned.columns:
        original_aligned["id"] = -(np.arange(len(original_aligned)) + 1)

    # align column order
    original_aligned = original_aligned[train_comp.columns]

    train_full = pd.concat([train_comp, original_aligned], ignore_index=True)
    train_full["is_external"] = [0] * len(train_comp) + [1] * len(original_aligned)
else:
    train_full = train_comp.copy()
    train_full["is_external"] = 0

# use concatenated data for downstream
train = train_full

Using Kaggle mounted competition data: /kaggle/input/competitions/playground-series-s6e2
train: (630000, 15) test: (270000, 14) sub: (270000, 2) original: None
DATA_SRC: kaggle

In [4]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
RANDOM_STATE = 42
torch.manual_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)
if DEVICE == "cuda":
    torch.cuda.manual_seed_all(RANDOM_STATE)
    torch.set_float32_matmul_precision("high")
N_FOLDS = 5
USE_ALL_CAT = True

print(f"Using device: {DEVICE}")

Using device: cuda

### Data download

In [5]:
display(train.head())
display(test.head())
display(sub.head())

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease,is_external
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,1,0
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,0,0
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,0,0
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,0,0
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,1,0

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7

       id  Heart Disease
0  630000              0
1  630001              0
2  630002              0
3  630003              0
4  630004              0

In [6]:
# Shapes
print("train:", train.shape)
print("test:", test.shape)

# Column diffs
train_cols = set(train.columns)
test_cols = set(test.columns)
print("Only in train:", sorted(train_cols - test_cols))
print("Only in test:", sorted(test_cols - train_cols))

# dtypes
train.dtypes.to_frame("dtype").head(30)

train: (630000, 16)
test: (270000, 14)
Only in train: ['Heart Disease', 'is_external']
Only in test: []

                           dtype
id                         int64
Age                        int64
Sex                        int64
Chest pain type            int64
BP                         int64
Cholesterol                int64
FBS over 120               int64
EKG results                int64
Max HR                     int64
Exercise angina            int64
ST depression            float64
Slope of ST                int64
Number of vessels fluro    int64
Thallium                   int64
Heart Disease              int64
is_external                int64

### Data Preprocessing

In [7]:
def encode_target_strict(y: pd.Series) -> pd.Series:
    """Map common string labels to {0,1}. Raises if unknown."""
    mapping_candidates = [
        {"No": 0, "Yes": 1},
        {"N": 0, "Y": 1},
        {"Negative": 0, "Positive": 1},
        {"Absent": 0, "Present": 1},
        {"Absence": 0, "Presence": 1},
        {0: 0, 1: 1},
        {"0": 0, "1": 1},
    ]
    uniq = set(pd.Series(y).dropna().unique().tolist())
    for mp in mapping_candidates:
        if uniq.issubset(set(mp.keys())):
            return pd.Series(y).map(mp).astype("int8")
    raise ValueError(f"Unknown target labels: {sorted(list(uniq))}")


# ---- target ----
if not pd.api.types.is_numeric_dtype(train["Heart Disease"]):
    train["Heart Disease"] = encode_target_strict(train["Heart Disease"])
if original is not None and "Heart Disease" in original.columns:
    if not pd.api.types.is_numeric_dtype(original["Heart Disease"]):
        original["Heart Disease"] = encode_target_strict(original["Heart Disease"])

TARGET_COL = "Heart Disease"
ID_COL = "id"
META_COLS = [TARGET_COL, ID_COL, "is_external"]

BASE_FEATURES = [c for c in train.columns if c not in META_COLS]

# Canonical S6E2 semantic categoricals (keep as category for embeddings/encoding)
CANONICAL_CAT = {
    "Sex",
    "Chest pain type",
    "FBS over 120",
    "EKG results",
    "Exercise angina",
    "Slope of ST",
    "Number of vessels fluro",
    "Thallium",
}

def split_cols(df: pd.DataFrame):
    base = [c for c in df.columns if c not in META_COLS]
    cat = [c for c in base if c in CANONICAL_CAT]
    num = [c for c in base if c not in cat]
    return cat, num


def add_external_target_stats(df: pd.DataFrame, original_df: pd.DataFrame | None) -> pd.DataFrame:
    """Merge group-wise target stats from the external/original dataset.
    Safe in Playground comps because original_df labels are not the competition labels.
    """
    if original_df is None:
        return df.copy()

    out = df.copy()
    initial_rows = len(out)

    for col in BASE_FEATURES:
        if col not in original_df.columns:
            continue

        stats = (
            original_df.groupby(col)[TARGET_COL]
            .agg(["mean", "median", "std", "skew", "count"])
            .reset_index()
        )
        stats.columns = [col] + [f"orig_{col}_{s}" for s in ["mean", "median", "std", "skew", "count"]]

        out = out.merge(stats, on=col, how="left")
        if len(out) != initial_rows:
            raise ValueError(f"Merge expanded rows for column {col}! {initial_rows} -> {len(out)}")

        # fill NAs for unseen values
        global_mean = float(original_df[TARGET_COL].mean())
        global_median = float(original_df[TARGET_COL].median())
        fill = {
            f"orig_{col}_mean": global_mean,
            f"orig_{col}_median": global_median,
            f"orig_{col}_std": 0.0,
            f"orig_{col}_skew": 0.0,
            f"orig_{col}_count": 0.0,
        }
        out = out.fillna(value=fill)

    return out



def build_features(
    train_fe: pd.DataFrame,
    test_fe: pd.DataFrame,
    cat_cols: list[str],
    num_cols: list[str],
):
    tr = train_fe.copy()
    te = test_fe.copy()

    # Keep only original + orig_* stats (no periodic/frequency encodings)
    print(f"Train Shape after FE: {tr.shape}")
    print(f"Test Shape after FE:  {te.shape}")

    # ---- Build X/y with clean dtypes ----
    drop_tr = [c for c in META_COLS if c in tr.columns]
    drop_te = [c for c in [ID_COL] if c in te.columns]

    X = tr.drop(columns=drop_tr).copy()
    X_test = te.drop(columns=drop_te).copy()
    y = tr[TARGET_COL].copy()

    cat_cols_final = [c for c in X.columns if c in cat_cols]
    num_cols_final = [c for c in X.columns if c not in cat_cols_final]

    # Ensure no overlap
    assert set(cat_cols_final).isdisjoint(set(num_cols_final))

    for c in cat_cols_final:
        combined = pd.concat([X[c], X_test[c]], axis=0, ignore_index=True)
        cats = pd.Categorical(combined).categories
        X[c] = pd.Categorical(X[c], categories=cats)
        X_test[c] = pd.Categorical(X_test[c], categories=cats)

    for c in num_cols_final:
        X[c] = pd.to_numeric(X[c], errors="coerce").astype("float32")
        X_test[c] = pd.to_numeric(X_test[c], errors="coerce").astype("float32")

    return X, X_test, y, cat_cols_final, num_cols_final


# ---- Feature engineering: match realmlp-ext-target-stats-5-fold-cv ----

# 1) External target stats, same idea as add_engineered_features in the CV notebook
train_fe = add_external_target_stats(train, original)
test_fe  = add_external_target_stats(test, original)

print("Train Shape after FE:", train_fe.shape)
print("Test Shape after FE: ", test_fe.shape)

# 2) Build X, y, X_test just like realmlp-ext-target-stats-5-fold-cv
#    base_features = all columns except target + id
TARGET_COL = "Heart Disease"
ID_COL = "id"

X = train_fe.drop(columns=[ID_COL, TARGET_COL])
y = train_fe[TARGET_COL].astype("int8")
X_test = test_fe.drop(columns=[ID_COL])

# Align columns (train has is_external, test does not)
X = X.drop(columns=["is_external"], errors="ignore")

print("X Shape:", X.shape)
print("X_test Shape:", X_test.shape)

# 3) Optional but close to the CV notebook: treat everything as categorical for RealMLP
#    (In the CV notebook they did astype(str).astype('category') on all columns.)
for col in X.columns:
    X[col] = X[col].astype(str).astype("category")
    X_test[col] = X_test[col].astype(str).astype("category")

# We'll let RealMLP infer categorical columns from dtype, so we don't need cat_cols here.
cat_cols = list(X.columns)

Train Shape after FE: (630000, 16)
Test Shape after FE:  (270000, 14)
X Shape: (630000, 13)
X_test Shape: (270000, 13)

### Data Quality Check

In [8]:
def check_data_quality(df, name="Dataset"):
    print(f"--- Data Quality: {name} ---")
    print(f"Total Rows: {len(df)}")

    cols_to_check = [c for c in df.columns if c != 'id']
    dupes = df.duplicated(subset=cols_to_check).sum()

    nan_counts = df.isnull().sum()
    total_nans = nan_counts.sum()

    print(f"Duplicate Rows (excl. ID): {dupes}")
    print(f"Total NaN values: {total_nans}")
    if total_nans > 0:
        print("\nColumns with NaNs:")
        print(nan_counts[nan_counts > 0])
    print("-" * 30)

check_data_quality(train, "Train")
check_data_quality(test, "Test")

--- Data Quality: Train ---
Total Rows: 630000
Duplicate Rows (excl. ID): 0
Total NaN values: 0
------------------------------
--- Data Quality: Test ---
Total Rows: 270000
Duplicate Rows (excl. ID): 0
Total NaN values: 0
------------------------------

### Feature Uniqueness & Cardinality

In [9]:
# Target distribution analysis

def analyze_uniqueness(df):
    unique_stats = []
    for col in df.columns:
        if col == 'id':
            continue

        n_unique = df[col].nunique()
        dtype = df[col].dtype

        category_guess = "Categorical/Ordinal" if n_unique < 25 else "Continuous"

        if pd.api.types.is_numeric_dtype(df[col]):
            mean_val = float(pd.to_numeric(df[col], errors='coerce').mean())
            std_val = float(pd.to_numeric(df[col], errors='coerce').std())
        else:
            mean_val = float('nan')
            std_val = float('nan')

        unique_stats.append({
            'Feature': col,
            'Unique Values': n_unique,
            'Data Type': dtype,
            'Heuristic Type': category_guess,
            'Mean': mean_val,
            'Std': std_val,
        })

    return pd.DataFrame(unique_stats).sort_values(by='Unique Values')

# class imbalance
comp_mask = (train["is_external"] == 0)
ext_mask  = (train["is_external"] == 1)

print("=== Target distribution: COMP ONLY ===")
print(train.loc[comp_mask, TARGET_COL].value_counts(dropna=False))
print(train.loc[comp_mask, TARGET_COL].value_counts(normalize=True, dropna=False))

print("\n=== Target distribution: EXTERNAL ONLY ===")
print(train.loc[ext_mask, TARGET_COL].value_counts(dropna=False))
print(train.loc[ext_mask, TARGET_COL].value_counts(normalize=True, dropna=False))

print("\n=== Target distribution: MERGED (comp + external) ===")
print(train[TARGET_COL].value_counts(dropna=False))
print(train[TARGET_COL].value_counts(normalize=True, dropna=False))

uniqueness_df = analyze_uniqueness(train)
uniqueness_df

=== Target distribution: COMP ONLY ===
Heart Disease
0    347546
1    282454
Name: count, dtype: int64
Heart Disease
0    0.55166
1    0.44834
Name: proportion, dtype: float64

=== Target distribution: EXTERNAL ONLY ===
Series([], Name: count, dtype: int64)
Series([], Name: proportion, dtype: float64)

=== Target distribution: MERGED (comp + external) ===
Heart Disease
0    347546
1    282454
Name: count, dtype: int64
Heart Disease
0    0.55166
1    0.44834
Name: proportion, dtype: float64

,Feature,Unique Values,Data Type,Heuristic Type,Mean,Std
14,is_external,1,int64,Categorical/Ordinal,0.000000,0.000000
1,Sex,2,int64,Categorical/Ordinal,0.714735,0.451541
8,Exercise angina,2,int64,Categorical/Ordinal,0.273725,0.445870
5,FBS over 120,2,int64,Categorical/Ordinal,0.079987,0.271274
13,Heart Disease,2,int64,Categorical/Ordinal,0.448340,0.497324
10,Slope of ST,3,int64,Categorical/Ordinal,1.455871,0.545192
6,EKG results,3,int64,Categorical/Ordinal,0.981660,0.998783
12,Thallium,3,int64,Categorical/Ordinal,4.618873,1.950007
2,Chest pain type,4,int64,Categorical/Ordinal,3.312752,0.851615
11,Number of vessels fluro,4,int64,Categorical/Ordinal,0.451040,0.798549
0,Age,42,int64,Continuous,54.136706,8.256301
3,BP,66,int64,Continuous,130.497433,14.975802
9,ST depression,66,float64,Continuous,0.716028,0.948472
7,Max HR,93,int64,Continuous,152.816763,19.112927
4,Cholesterol,150,int64,Continuous,245.011814,33.681581

### Visualize Top Skewed Features

In [10]:
numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()

skew_series = X[numeric_cols].skew().abs().sort_values(ascending=False)
top_skewed_features = skew_series.head(6).index.tolist()

print("Top 6 Most Skewed Features (Absolute Values):")
print(X[top_skewed_features].skew())

plt.figure(figsize=(16, 10))
for i, col in enumerate(top_skewed_features):
    plt.subplot(2, 3, i + 1)
    sns.histplot(X[col].sample(min(10000, len(X))), kde=True, color='teal', bins=30)
    plt.title(f"Feature: {col}\nSkewness: {X[col].skew():.2f}")
    plt.xlabel("")
    plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

Top 6 Most Skewed Features (Absolute Values):
Series([], dtype: float64)

### Cross-validation setup (competition rows only)

In [11]:
ID_COL = "id"
TARGET_COL = "Heart Disease"

# Competition rows only (is_external == 0)
comp_mask = (train["is_external"] == 0).values

X_comp = X.loc[comp_mask].reset_index(drop=True)
y_comp = y.loc[comp_mask].reset_index(drop=True)
comp_ids = train.loc[comp_mask, ID_COL].reset_index(drop=True)

X_test_comp = X_test.copy()
test_ids = test[ID_COL].reset_index(drop=True)

print("X_comp:", X_comp.shape)
print("y_comp:", y_comp.shape)
print("X_test_comp:", X_test_comp.shape)

skf = StratifiedKFold(
    n_splits=N_FOLDS,
    shuffle=True,
    random_state=RANDOM_STATE,
)

X_comp: (630000, 13)
y_comp: (630000,)
X_test_comp: (270000, 13)

### Base model and training

In [12]:
param_grid = {
        # 'device': 'cuda',
        'random_state': 42,
        'verbosity': 2,
        'n_epochs': 100,
        'batch_size': 2**12,
        'n_ens': 8,
        'use_early_stopping': True,
        'early_stopping_additive_patience': 20,
        'early_stopping_multiplicative_patience': 1,
        'act': "mish",
        'embedding_size': 8,
        'first_layer_lr_factor': 0.5962121993798933,
        'val_metric_name': '1-auc_ovr',
        'hidden_sizes': "rectangular",
        'hidden_width': 384,
        'lr': 0.04,
        'ls_eps': 0.011498317194338772,
        'ls_eps_sched': "coslog4",
        'max_one_hot_cat_size': 18,
        'n_hidden_layers': 4,
        'p_drop': 0.07301419697186451,
        'p_drop_sched': "flat_cos",
        'plr_hidden_1': 16,
        'plr_hidden_2': 8,
        'plr_lr_factor': 0.1151437622270563,
        'plr_sigma': 2.3316811282666916,
        'scale_lr_factor': 2.244801835541429,
        'sq_mom': 1.0 - 0.011834054955582318,
        'wd': 0.02369230879235962,
    }
param_grid['device'] = DEVICE


def make_model(param_grid, cat_cols):
    try:
        return RealMLP_TD_Classifier(**param_grid, cat_col_names=cat_cols)
    except TypeError:
        # Older pytabkit versions may not support cat_col_names
        return RealMLP_TD_Classifier(**param_grid)


SEEDS = [42, 2024, 2025]

test_ensemble = np.zeros(len(X_test_comp), dtype="float32")
oof_ensemble = np.zeros(len(X_comp), dtype="float32")

for seed in SEEDS:
    print(f"\n==== SEED {seed} ====")
    param_grid['random_state'] = seed

    oof_realmlp = np.zeros(len(X_comp), dtype="float32")
    test_realmlp = np.zeros(len(X_test_comp), dtype="float32")
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_comp, y_comp), start=1):
        print(f"\n--- RealMLP Fold {fold}/{N_FOLDS} ---")

        X_tr, X_val = X_comp.iloc[train_idx], X_comp.iloc[val_idx]
        y_tr, y_val = y_comp.iloc[train_idx], y_comp.iloc[val_idx]

        model = make_model(param_grid, cat_cols)
        model.fit(X_tr, y_tr.values, X_val, y_val.values)

        val_probs = model.predict_proba(X_val)[:, 1]
        test_probs = model.predict_proba(X_test_comp)[:, 1]

        oof_realmlp[val_idx] = val_probs.astype("float32")
        test_realmlp += (test_probs / N_FOLDS).astype("float32")

        score = roc_auc_score(y_val, val_probs)
        fold_scores.append(score)
        print(f"Fold {fold} ROC-AUC: {score:.6f}")

        if DEVICE == 'cuda':
            torch.cuda.empty_cache()

    print(f"\n[RealMLP][seed={seed}] OOF AUC = {roc_auc_score(y_comp, oof_realmlp):.6f}")
    print("Fold scores:", fold_scores)

    oof_ensemble += oof_realmlp / len(SEEDS)
    test_ensemble += test_realmlp / len(SEEDS)

print(f"\n[RealMLP][ensemble] OOF AUC = {roc_auc_score(y_comp, oof_ensemble):.6f}")

==== SEED 42 ====

--- RealMLP Fold 1/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.047396
Epoch 2/100: val 1-auc_ovr = 0.044425
Epoch 3/100: val 1-auc_ovr = 0.043934
Epoch 4/100: val 1-auc_ovr = 0.043966
Epoch 5/100: val 1-auc_ovr = 0.043908
Epoch 6/100: val 1-auc_ovr = 0.043883
Epoch 7/100: val 1-auc_ovr = 0.043881
Epoch 8/100: val 1-auc_ovr = 0.043909
Epoch 9/100: val 1-auc_ovr = 0.043943
Epoch 10/100: val 1-auc_ovr = 0.043965
Epoch 11/100: val 1-auc_ovr = 0.043936
Epoch 12/100: val 1-auc_ovr = 0.043983
Epoch 13/100: val 1-auc_ovr = 0.043933
Epoch 14/100: val 1-auc_ovr = 0.043955
Epoch 15/100: val 1-auc_ovr = 0.043933
Epoch 16/100: val 1-auc_ovr = 0.043922
Epoch 17/100: val 1-auc_ovr = 0.043947
Epoch 18/100: val 1-auc_ovr = 0.043961
Epoch 19/100: val 1-auc_ovr = 0.043973
Epoch 20/100: val 1-auc_ovr = 0.043979
Epoch 21/100: val 1-auc_ovr = 0.043983
Epoch 22/100: val 1-auc_ovr = 0.043984
Epoch 23/100: val 1-auc_ovr = 0.044007
Epoch 24/100: val 1-auc_ovr = 0.044003
Epoch 25/100: val 1-auc_ovr = 0.043981
Epoch 26/100: val 1-auc_ovr = 0.043980
Epoch 27/100: val 1-auc_ovr = 0.044012
Epoch 28/100: val 1-auc_ovr = 0.044000

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 1 ROC-AUC: 0.956119

--- RealMLP Fold 2/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048295
Epoch 2/100: val 1-auc_ovr = 0.045527
Epoch 3/100: val 1-auc_ovr = 0.045139
Epoch 4/100: val 1-auc_ovr = 0.045111
Epoch 5/100: val 1-auc_ovr = 0.045088
Epoch 6/100: val 1-auc_ovr = 0.045063
Epoch 7/100: val 1-auc_ovr = 0.045065
Epoch 8/100: val 1-auc_ovr = 0.045070
Epoch 9/100: val 1-auc_ovr = 0.045121
Epoch 10/100: val 1-auc_ovr = 0.045085
Epoch 11/100: val 1-auc_ovr = 0.045113
Epoch 12/100: val 1-auc_ovr = 0.045086
Epoch 13/100: val 1-auc_ovr = 0.045102
Epoch 14/100: val 1-auc_ovr = 0.045147
Epoch 15/100: val 1-auc_ovr = 0.045075
Epoch 16/100: val 1-auc_ovr = 0.045104
Epoch 17/100: val 1-auc_ovr = 0.045117
Epoch 18/100: val 1-auc_ovr = 0.045140
Epoch 19/100: val 1-auc_ovr = 0.045140
Epoch 20/100: val 1-auc_ovr = 0.045148
Epoch 21/100: val 1-auc_ovr = 0.045157
Epoch 22/100: val 1-auc_ovr = 0.045161
Epoch 23/100: val 1-auc_ovr = 0.045179
Epoch 24/100: val 1-auc_ovr = 0.045170
Epoch 25/100: val 1-auc_ovr = 0.045124
Epoch 26/100: val 1-auc_ovr = 0.045150
Epoch 27/100: val 1-auc_ovr = 0.045161

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 2 ROC-AUC: 0.954937

--- RealMLP Fold 3/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048301
Epoch 2/100: val 1-auc_ovr = 0.044772
Epoch 3/100: val 1-auc_ovr = 0.044333
Epoch 4/100: val 1-auc_ovr = 0.044297
Epoch 5/100: val 1-auc_ovr = 0.044234
Epoch 6/100: val 1-auc_ovr = 0.044235
Epoch 7/100: val 1-auc_ovr = 0.044232
Epoch 8/100: val 1-auc_ovr = 0.044246
Epoch 9/100: val 1-auc_ovr = 0.044234
Epoch 10/100: val 1-auc_ovr = 0.044274
Epoch 11/100: val 1-auc_ovr = 0.044300
Epoch 12/100: val 1-auc_ovr = 0.044310
Epoch 13/100: val 1-auc_ovr = 0.044264
Epoch 14/100: val 1-auc_ovr = 0.044288
Epoch 15/100: val 1-auc_ovr = 0.044233
Epoch 16/100: val 1-auc_ovr = 0.044262
Epoch 17/100: val 1-auc_ovr = 0.044251
Epoch 18/100: val 1-auc_ovr = 0.044299
Epoch 19/100: val 1-auc_ovr = 0.044326
Epoch 20/100: val 1-auc_ovr = 0.044326
Epoch 21/100: val 1-auc_ovr = 0.044337
Epoch 22/100: val 1-auc_ovr = 0.044352
Epoch 23/100: val 1-auc_ovr = 0.044350
Epoch 24/100: val 1-auc_ovr = 0.044362
Epoch 25/100: val 1-auc_ovr = 0.044346
Epoch 26/100: val 1-auc_ovr = 0.044342
Epoch 27/100: val 1-auc_ovr = 0.044386
Epoch 28/100: val 1-auc_ovr = 0.044378

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 3 ROC-AUC: 0.955768

--- RealMLP Fold 4/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048387
Epoch 2/100: val 1-auc_ovr = 0.045053
Epoch 3/100: val 1-auc_ovr = 0.044697
Epoch 4/100: val 1-auc_ovr = 0.044637
Epoch 5/100: val 1-auc_ovr = 0.044598
Epoch 6/100: val 1-auc_ovr = 0.044571
Epoch 7/100: val 1-auc_ovr = 0.044569
Epoch 8/100: val 1-auc_ovr = 0.044589
Epoch 9/100: val 1-auc_ovr = 0.044585
Epoch 10/100: val 1-auc_ovr = 0.044589
Epoch 11/100: val 1-auc_ovr = 0.044589
Epoch 12/100: val 1-auc_ovr = 0.044620
Epoch 13/100: val 1-auc_ovr = 0.044635
Epoch 14/100: val 1-auc_ovr = 0.044611
Epoch 15/100: val 1-auc_ovr = 0.044564
Epoch 16/100: val 1-auc_ovr = 0.044589
Epoch 17/100: val 1-auc_ovr = 0.044586
Epoch 18/100: val 1-auc_ovr = 0.044590
Epoch 19/100: val 1-auc_ovr = 0.044611
Epoch 20/100: val 1-auc_ovr = 0.044613
Epoch 21/100: val 1-auc_ovr = 0.044620
Epoch 22/100: val 1-auc_ovr = 0.044630
Epoch 23/100: val 1-auc_ovr = 0.044623
Epoch 24/100: val 1-auc_ovr = 0.044650
Epoch 25/100: val 1-auc_ovr = 0.044624
Epoch 26/100: val 1-auc_ovr = 0.044596
Epoch 27/100: val 1-auc_ovr = 0.044636
Epoch 28/100: val 1-auc_ovr = 0.044666
Epoch 29/100: val 1-auc_ovr = 0.044617
Epoch 30/100: val 1-auc_ovr = 0.044706
Epoch 31/100: val 1-auc_ovr = 0.044672
Epoch 32/100: val 1-auc_ovr = 0.044696
Epoch 33/100: val 1-auc_ovr = 0.044690
Epoch 34/100: val 1-auc_ovr = 0.044681
Epoch 35/100: val 1-auc_ovr = 0.044684
Epoch 36/100: val 1-auc_ovr = 0.044756

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 4 ROC-AUC: 0.955436

--- RealMLP Fold 5/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.047628
Epoch 2/100: val 1-auc_ovr = 0.044322
Epoch 3/100: val 1-auc_ovr = 0.043898
Epoch 4/100: val 1-auc_ovr = 0.043818
Epoch 5/100: val 1-auc_ovr = 0.043801
Epoch 6/100: val 1-auc_ovr = 0.043785
Epoch 7/100: val 1-auc_ovr = 0.043774
Epoch 8/100: val 1-auc_ovr = 0.043792
Epoch 9/100: val 1-auc_ovr = 0.043812
Epoch 10/100: val 1-auc_ovr = 0.043804
Epoch 11/100: val 1-auc_ovr = 0.043865
Epoch 12/100: val 1-auc_ovr = 0.043801
Epoch 13/100: val 1-auc_ovr = 0.043811
Epoch 14/100: val 1-auc_ovr = 0.043784
Epoch 15/100: val 1-auc_ovr = 0.043829
Epoch 16/100: val 1-auc_ovr = 0.043795
Epoch 17/100: val 1-auc_ovr = 0.043799
Epoch 18/100: val 1-auc_ovr = 0.043831
Epoch 19/100: val 1-auc_ovr = 0.043840
Epoch 20/100: val 1-auc_ovr = 0.043843
Epoch 21/100: val 1-auc_ovr = 0.043851
Epoch 22/100: val 1-auc_ovr = 0.043857
Epoch 23/100: val 1-auc_ovr = 0.043858
Epoch 24/100: val 1-auc_ovr = 0.043841
Epoch 25/100: val 1-auc_ovr = 0.043835
Epoch 26/100: val 1-auc_ovr = 0.043846
Epoch 27/100: val 1-auc_ovr = 0.043855
Epoch 28/100: val 1-auc_ovr = 0.043880

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 5 ROC-AUC: 0.956226

[RealMLP][seed=42] OOF AUC = 0.955657
Fold scores: [np.float64(0.9561193722320547), np.float64(0.9549367551920123), np.float64(0.9557678578357581), np.float64(0.9554355848611984), np.float64(0.9562259483022535)]

==== SEED 2024 ====

--- RealMLP Fold 1/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048382
Epoch 2/100: val 1-auc_ovr = 0.044481
Epoch 3/100: val 1-auc_ovr = 0.044016
Epoch 4/100: val 1-auc_ovr = 0.043938
Epoch 5/100: val 1-auc_ovr = 0.043912
Epoch 6/100: val 1-auc_ovr = 0.043874
Epoch 7/100: val 1-auc_ovr = 0.043879
Epoch 8/100: val 1-auc_ovr = 0.043894
Epoch 9/100: val 1-auc_ovr = 0.043937
Epoch 10/100: val 1-auc_ovr = 0.043935
Epoch 11/100: val 1-auc_ovr = 0.044007
Epoch 12/100: val 1-auc_ovr = 0.043992
Epoch 13/100: val 1-auc_ovr = 0.043967
Epoch 14/100: val 1-auc_ovr = 0.043929
Epoch 15/100: val 1-auc_ovr = 0.043937
Epoch 16/100: val 1-auc_ovr = 0.043946
Epoch 17/100: val 1-auc_ovr = 0.043954
Epoch 18/100: val 1-auc_ovr = 0.043961
Epoch 19/100: val 1-auc_ovr = 0.043975
Epoch 20/100: val 1-auc_ovr = 0.043976
Epoch 21/100: val 1-auc_ovr = 0.043980
Epoch 22/100: val 1-auc_ovr = 0.043994
Epoch 23/100: val 1-auc_ovr = 0.044000
Epoch 24/100: val 1-auc_ovr = 0.043978
Epoch 25/100: val 1-auc_ovr = 0.043979
Epoch 26/100: val 1-auc_ovr = 0.043991
Epoch 27/100: val 1-auc_ovr = 0.044063

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 1 ROC-AUC: 0.956126

--- RealMLP Fold 2/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.049291
Epoch 2/100: val 1-auc_ovr = 0.045592
Epoch 3/100: val 1-auc_ovr = 0.045178
Epoch 4/100: val 1-auc_ovr = 0.045121
Epoch 5/100: val 1-auc_ovr = 0.045121
Epoch 6/100: val 1-auc_ovr = 0.045074
Epoch 7/100: val 1-auc_ovr = 0.045077
Epoch 8/100: val 1-auc_ovr = 0.045060
Epoch 9/100: val 1-auc_ovr = 0.045083
Epoch 10/100: val 1-auc_ovr = 0.045155
Epoch 11/100: val 1-auc_ovr = 0.045122
Epoch 12/100: val 1-auc_ovr = 0.045112
Epoch 13/100: val 1-auc_ovr = 0.045147
Epoch 14/100: val 1-auc_ovr = 0.045092
Epoch 15/100: val 1-auc_ovr = 0.045075
Epoch 16/100: val 1-auc_ovr = 0.045080
Epoch 17/100: val 1-auc_ovr = 0.045088
Epoch 18/100: val 1-auc_ovr = 0.045125
Epoch 19/100: val 1-auc_ovr = 0.045148
Epoch 20/100: val 1-auc_ovr = 0.045147
Epoch 21/100: val 1-auc_ovr = 0.045148
Epoch 22/100: val 1-auc_ovr = 0.045162
Epoch 23/100: val 1-auc_ovr = 0.045177
Epoch 24/100: val 1-auc_ovr = 0.045150
Epoch 25/100: val 1-auc_ovr = 0.045194
Epoch 26/100: val 1-auc_ovr = 0.045106
Epoch 27/100: val 1-auc_ovr = 0.045159
Epoch 28/100: val 1-auc_ovr = 0.045123
Epoch 29/100: val 1-auc_ovr = 0.045176

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 2 ROC-AUC: 0.954940

--- RealMLP Fold 3/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.049119
Epoch 2/100: val 1-auc_ovr = 0.044825
Epoch 3/100: val 1-auc_ovr = 0.044398
Epoch 4/100: val 1-auc_ovr = 0.044340
Epoch 5/100: val 1-auc_ovr = 0.044264
Epoch 6/100: val 1-auc_ovr = 0.044217
Epoch 7/100: val 1-auc_ovr = 0.044220
Epoch 8/100: val 1-auc_ovr = 0.044232
Epoch 9/100: val 1-auc_ovr = 0.044265
Epoch 10/100: val 1-auc_ovr = 0.044269
Epoch 11/100: val 1-auc_ovr = 0.044225
Epoch 12/100: val 1-auc_ovr = 0.044280
Epoch 13/100: val 1-auc_ovr = 0.044343
Epoch 14/100: val 1-auc_ovr = 0.044274
Epoch 15/100: val 1-auc_ovr = 0.044238
Epoch 16/100: val 1-auc_ovr = 0.044254
Epoch 17/100: val 1-auc_ovr = 0.044257
Epoch 18/100: val 1-auc_ovr = 0.044311
Epoch 19/100: val 1-auc_ovr = 0.044324
Epoch 20/100: val 1-auc_ovr = 0.044331
Epoch 21/100: val 1-auc_ovr = 0.044336
Epoch 22/100: val 1-auc_ovr = 0.044347
Epoch 23/100: val 1-auc_ovr = 0.044361
Epoch 24/100: val 1-auc_ovr = 0.044324
Epoch 25/100: val 1-auc_ovr = 0.044370
Epoch 26/100: val 1-auc_ovr = 0.044324
Epoch 27/100: val 1-auc_ovr = 0.044298

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 3 ROC-AUC: 0.955783

--- RealMLP Fold 4/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.049167
Epoch 2/100: val 1-auc_ovr = 0.045125
Epoch 3/100: val 1-auc_ovr = 0.044698
Epoch 4/100: val 1-auc_ovr = 0.044600
Epoch 5/100: val 1-auc_ovr = 0.044570
Epoch 6/100: val 1-auc_ovr = 0.044570
Epoch 7/100: val 1-auc_ovr = 0.044561
Epoch 8/100: val 1-auc_ovr = 0.044566
Epoch 9/100: val 1-auc_ovr = 0.044571
Epoch 10/100: val 1-auc_ovr = 0.044592
Epoch 11/100: val 1-auc_ovr = 0.044574
Epoch 12/100: val 1-auc_ovr = 0.044610
Epoch 13/100: val 1-auc_ovr = 0.044595
Epoch 14/100: val 1-auc_ovr = 0.044601
Epoch 15/100: val 1-auc_ovr = 0.044585
Epoch 16/100: val 1-auc_ovr = 0.044598
Epoch 17/100: val 1-auc_ovr = 0.044584
Epoch 18/100: val 1-auc_ovr = 0.044604
Epoch 19/100: val 1-auc_ovr = 0.044602
Epoch 20/100: val 1-auc_ovr = 0.044605
Epoch 21/100: val 1-auc_ovr = 0.044612
Epoch 22/100: val 1-auc_ovr = 0.044622
Epoch 23/100: val 1-auc_ovr = 0.044615
Epoch 24/100: val 1-auc_ovr = 0.044597
Epoch 25/100: val 1-auc_ovr = 0.044621
Epoch 26/100: val 1-auc_ovr = 0.044618
Epoch 27/100: val 1-auc_ovr = 0.044642
Epoch 28/100: val 1-auc_ovr = 0.044618

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 4 ROC-AUC: 0.955439

--- RealMLP Fold 5/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048456
Epoch 2/100: val 1-auc_ovr = 0.044380
Epoch 3/100: val 1-auc_ovr = 0.043933
Epoch 4/100: val 1-auc_ovr = 0.043845
Epoch 5/100: val 1-auc_ovr = 0.043823
Epoch 6/100: val 1-auc_ovr = 0.043794
Epoch 7/100: val 1-auc_ovr = 0.043786
Epoch 8/100: val 1-auc_ovr = 0.043795
Epoch 9/100: val 1-auc_ovr = 0.043786
Epoch 10/100: val 1-auc_ovr = 0.043792
Epoch 11/100: val 1-auc_ovr = 0.043886
Epoch 12/100: val 1-auc_ovr = 0.043795
Epoch 13/100: val 1-auc_ovr = 0.043836
Epoch 14/100: val 1-auc_ovr = 0.043807
Epoch 15/100: val 1-auc_ovr = 0.043806
Epoch 16/100: val 1-auc_ovr = 0.043796
Epoch 17/100: val 1-auc_ovr = 0.043794
Epoch 18/100: val 1-auc_ovr = 0.043834
Epoch 19/100: val 1-auc_ovr = 0.043853
Epoch 20/100: val 1-auc_ovr = 0.043854
Epoch 21/100: val 1-auc_ovr = 0.043857
Epoch 22/100: val 1-auc_ovr = 0.043864
Epoch 23/100: val 1-auc_ovr = 0.043862
Epoch 24/100: val 1-auc_ovr = 0.043909
Epoch 25/100: val 1-auc_ovr = 0.043876
Epoch 26/100: val 1-auc_ovr = 0.043858
Epoch 27/100: val 1-auc_ovr = 0.043830
Epoch 28/100: val 1-auc_ovr = 0.043863
Epoch 29/100: val 1-auc_ovr = 0.043868
Epoch 30/100: val 1-auc_ovr = 0.043876

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 5 ROC-AUC: 0.956214

[RealMLP][seed=2024] OOF AUC = 0.955659
Fold scores: [np.float64(0.9561260731385418), np.float64(0.9549397235112417), np.float64(0.9557833800404708), np.float64(0.9554387240647488), np.float64(0.9562137439124168)]

==== SEED 2025 ====

--- RealMLP Fold 1/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.047987
Epoch 2/100: val 1-auc_ovr = 0.044480
Epoch 3/100: val 1-auc_ovr = 0.044041
Epoch 4/100: val 1-auc_ovr = 0.043956
Epoch 5/100: val 1-auc_ovr = 0.043908
Epoch 6/100: val 1-auc_ovr = 0.043888
Epoch 7/100: val 1-auc_ovr = 0.043888
Epoch 8/100: val 1-auc_ovr = 0.043892
Epoch 9/100: val 1-auc_ovr = 0.043938
Epoch 10/100: val 1-auc_ovr = 0.043944
Epoch 11/100: val 1-auc_ovr = 0.043914
Epoch 12/100: val 1-auc_ovr = 0.043946
Epoch 13/100: val 1-auc_ovr = 0.043929
Epoch 14/100: val 1-auc_ovr = 0.043928
Epoch 15/100: val 1-auc_ovr = 0.043932
Epoch 16/100: val 1-auc_ovr = 0.043917
Epoch 17/100: val 1-auc_ovr = 0.043950
Epoch 18/100: val 1-auc_ovr = 0.043961
Epoch 19/100: val 1-auc_ovr = 0.043971
Epoch 20/100: val 1-auc_ovr = 0.043975
Epoch 21/100: val 1-auc_ovr = 0.043979
Epoch 22/100: val 1-auc_ovr = 0.043999
Epoch 23/100: val 1-auc_ovr = 0.043995
Epoch 24/100: val 1-auc_ovr = 0.044013
Epoch 25/100: val 1-auc_ovr = 0.044019
Epoch 26/100: val 1-auc_ovr = 0.043997
Epoch 27/100: val 1-auc_ovr = 0.044011
Epoch 28/100: val 1-auc_ovr = 0.044084

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 1 ROC-AUC: 0.956112

--- RealMLP Fold 2/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048816
Epoch 2/100: val 1-auc_ovr = 0.045539
Epoch 3/100: val 1-auc_ovr = 0.045149
Epoch 4/100: val 1-auc_ovr = 0.045141
Epoch 5/100: val 1-auc_ovr = 0.045090
Epoch 6/100: val 1-auc_ovr = 0.045077
Epoch 7/100: val 1-auc_ovr = 0.045079
Epoch 8/100: val 1-auc_ovr = 0.045118
Epoch 9/100: val 1-auc_ovr = 0.045140
Epoch 10/100: val 1-auc_ovr = 0.045080
Epoch 11/100: val 1-auc_ovr = 0.045104
Epoch 12/100: val 1-auc_ovr = 0.045139
Epoch 13/100: val 1-auc_ovr = 0.045092
Epoch 14/100: val 1-auc_ovr = 0.045159
Epoch 15/100: val 1-auc_ovr = 0.045155
Epoch 16/100: val 1-auc_ovr = 0.045086
Epoch 17/100: val 1-auc_ovr = 0.045112
Epoch 18/100: val 1-auc_ovr = 0.045117
Epoch 19/100: val 1-auc_ovr = 0.045143
Epoch 20/100: val 1-auc_ovr = 0.045137
Epoch 21/100: val 1-auc_ovr = 0.045137
Epoch 22/100: val 1-auc_ovr = 0.045154
Epoch 23/100: val 1-auc_ovr = 0.045132
Epoch 24/100: val 1-auc_ovr = 0.045141
Epoch 25/100: val 1-auc_ovr = 0.045155
Epoch 26/100: val 1-auc_ovr = 0.045149
Epoch 27/100: val 1-auc_ovr = 0.045164

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 2 ROC-AUC: 0.954923

--- RealMLP Fold 3/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048458
Epoch 2/100: val 1-auc_ovr = 0.044734
Epoch 3/100: val 1-auc_ovr = 0.044330
Epoch 4/100: val 1-auc_ovr = 0.044272
Epoch 5/100: val 1-auc_ovr = 0.044263
Epoch 6/100: val 1-auc_ovr = 0.044230
Epoch 7/100: val 1-auc_ovr = 0.044229
Epoch 8/100: val 1-auc_ovr = 0.044253
Epoch 9/100: val 1-auc_ovr = 0.044254
Epoch 10/100: val 1-auc_ovr = 0.044282
Epoch 11/100: val 1-auc_ovr = 0.044269
Epoch 12/100: val 1-auc_ovr = 0.044336
Epoch 13/100: val 1-auc_ovr = 0.044251
Epoch 14/100: val 1-auc_ovr = 0.044295
Epoch 15/100: val 1-auc_ovr = 0.044285
Epoch 16/100: val 1-auc_ovr = 0.044273
Epoch 17/100: val 1-auc_ovr = 0.044318
Epoch 18/100: val 1-auc_ovr = 0.044315
Epoch 19/100: val 1-auc_ovr = 0.044332
Epoch 20/100: val 1-auc_ovr = 0.044334
Epoch 21/100: val 1-auc_ovr = 0.044346
Epoch 22/100: val 1-auc_ovr = 0.044359
Epoch 23/100: val 1-auc_ovr = 0.044378
Epoch 24/100: val 1-auc_ovr = 0.044364
Epoch 25/100: val 1-auc_ovr = 0.044369
Epoch 26/100: val 1-auc_ovr = 0.044348
Epoch 27/100: val 1-auc_ovr = 0.044333
Epoch 28/100: val 1-auc_ovr = 0.044351

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 3 ROC-AUC: 0.955771

--- RealMLP Fold 4/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048669
Epoch 2/100: val 1-auc_ovr = 0.045015
Epoch 3/100: val 1-auc_ovr = 0.044659
Epoch 4/100: val 1-auc_ovr = 0.044602
Epoch 5/100: val 1-auc_ovr = 0.044584
Epoch 6/100: val 1-auc_ovr = 0.044560
Epoch 7/100: val 1-auc_ovr = 0.044558
Epoch 8/100: val 1-auc_ovr = 0.044557
Epoch 9/100: val 1-auc_ovr = 0.044582
Epoch 10/100: val 1-auc_ovr = 0.044581
Epoch 11/100: val 1-auc_ovr = 0.044614
Epoch 12/100: val 1-auc_ovr = 0.044587
Epoch 13/100: val 1-auc_ovr = 0.044619
Epoch 14/100: val 1-auc_ovr = 0.044600
Epoch 15/100: val 1-auc_ovr = 0.044608
Epoch 16/100: val 1-auc_ovr = 0.044582
Epoch 17/100: val 1-auc_ovr = 0.044580
Epoch 18/100: val 1-auc_ovr = 0.044609
Epoch 19/100: val 1-auc_ovr = 0.044607
Epoch 20/100: val 1-auc_ovr = 0.044614
Epoch 21/100: val 1-auc_ovr = 0.044618
Epoch 22/100: val 1-auc_ovr = 0.044636
Epoch 23/100: val 1-auc_ovr = 0.044617
Epoch 24/100: val 1-auc_ovr = 0.044624
Epoch 25/100: val 1-auc_ovr = 0.044613
Epoch 26/100: val 1-auc_ovr = 0.044640
Epoch 27/100: val 1-auc_ovr = 0.044640
Epoch 28/100: val 1-auc_ovr = 0.044615
Epoch 29/100: val 1-auc_ovr = 0.044614

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 4 ROC-AUC: 0.955443

--- RealMLP Fold 5/5 ---
Columns classified as continuous: []
Columns classified as categorical: ['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium']

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Epoch 1/100: val 1-auc_ovr = 0.048191
Epoch 2/100: val 1-auc_ovr = 0.044206
Epoch 3/100: val 1-auc_ovr = 0.043932
Epoch 4/100: val 1-auc_ovr = 0.043864
Epoch 5/100: val 1-auc_ovr = 0.043815
Epoch 6/100: val 1-auc_ovr = 0.043782
Epoch 7/100: val 1-auc_ovr = 0.043779
Epoch 8/100: val 1-auc_ovr = 0.043778
Epoch 9/100: val 1-auc_ovr = 0.043790
Epoch 10/100: val 1-auc_ovr = 0.043787
Epoch 11/100: val 1-auc_ovr = 0.043803
Epoch 12/100: val 1-auc_ovr = 0.043805
Epoch 13/100: val 1-auc_ovr = 0.043787
Epoch 14/100: val 1-auc_ovr = 0.043797
Epoch 15/100: val 1-auc_ovr = 0.043810
Epoch 16/100: val 1-auc_ovr = 0.043795
Epoch 17/100: val 1-auc_ovr = 0.043817
Epoch 18/100: val 1-auc_ovr = 0.043841
Epoch 19/100: val 1-auc_ovr = 0.043858
Epoch 20/100: val 1-auc_ovr = 0.043865
Epoch 21/100: val 1-auc_ovr = 0.043875
Epoch 22/100: val 1-auc_ovr = 0.043868
Epoch 23/100: val 1-auc_ovr = 0.043869
Epoch 24/100: val 1-auc_ovr = 0.043862
Epoch 25/100: val 1-auc_ovr = 0.043904
Epoch 26/100: val 1-auc_ovr = 0.043874
Epoch 27/100: val 1-auc_ovr = 0.043883
Epoch 28/100: val 1-auc_ovr = 0.043821
Epoch 29/100: val 1-auc_ovr = 0.043917

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Fold 5 ROC-AUC: 0.956222

[RealMLP][seed=2025] OOF AUC = 0.955678
Fold scores: [np.float64(0.9561117225483129), np.float64(0.9549233723520363), np.float64(0.9557711224648345), np.float64(0.955442700244932), np.float64(0.9562218699854296)]

[RealMLP][ensemble] OOF AUC = 0.955689

### Submission

In [13]:
# ---- OOF 保存（解析用） ----
oof_df = pd.DataFrame({
    "id": comp_ids,
    "y_true": y_comp.values,
    "y_pred": oof_ensemble,
})
oof_df.to_csv("realmlp_oof.csv", index=False)
print("Saved: realmlp_oof.csv")

# ---- submission（RealMLP seed ensemble） ----
submission_realmlp = pd.DataFrame({
    "id": test_ids,
    "Heart Disease": test_ensemble,
})
submission_realmlp.to_csv("submission.csv", index=False)
print("Saved RealMLP submission, shape=", submission_realmlp.shape)

Saved: realmlp_oof.csv
Saved RealMLP submission, shape= (270000, 2)

In [14]:
def check_data_quality(df, name="Dataset"):
    print(f"--- Data Quality: {name} ---")
    print(f"Total Rows: {len(df)}")

    cols_to_check = [c for c in df.columns if c != 'id']
    dupes = df.duplicated(subset=cols_to_check).sum()

    nan_counts = df.isnull().sum()
    total_nans = nan_counts.sum()

    print(f"Duplicate Rows (excl. ID): {dupes}")
    print(f"Total NaN values: {total_nans}")
    if total_nans > 0:
        print("\nColumns with NaNs:")
        print(nan_counts[nan_counts > 0])
    print("-" * 30)

check_data_quality(train, "Train")
check_data_quality(test, "Test")

--- Data Quality: Train ---
Total Rows: 630000
Duplicate Rows (excl. ID): 0
Total NaN values: 0
------------------------------
--- Data Quality: Test ---
Total Rows: 270000
Duplicate Rows (excl. ID): 0
Total NaN values: 0
------------------------------

In [15]:
# Target distribution analysis

def analyze_uniqueness(df):
    unique_stats = []
    for col in df.columns:
        if col == 'id':
            continue

        n_unique = df[col].nunique()
        dtype = df[col].dtype

        category_guess = "Categorical/Ordinal" if n_unique < 25 else "Continuous"

        if pd.api.types.is_numeric_dtype(df[col]):
            mean_val = float(pd.to_numeric(df[col], errors='coerce').mean())
            std_val = float(pd.to_numeric(df[col], errors='coerce').std())
        else:
            mean_val = float('nan')
            std_val = float('nan')

        unique_stats.append({
            'Feature': col,
            'Unique Values': n_unique,
            'Data Type': dtype,
            'Heuristic Type': category_guess,
            'Mean': mean_val,
            'Std': std_val,
        })

    return pd.DataFrame(unique_stats).sort_values(by='Unique Values')

# class imbalance
comp_mask = (train["is_external"] == 0)
ext_mask  = (train["is_external"] == 1)

print("=== Target distribution: COMP ONLY ===")
print(train.loc[comp_mask, TARGET_COL].value_counts(dropna=False))
print(train.loc[comp_mask, TARGET_COL].value_counts(normalize=True, dropna=False))

print("\n=== Target distribution: EXTERNAL ONLY ===")
print(train.loc[ext_mask, TARGET_COL].value_counts(dropna=False))
print(train.loc[ext_mask, TARGET_COL].value_counts(normalize=True, dropna=False))

print("\n=== Target distribution: MERGED (comp + external) ===")
print(train[TARGET_COL].value_counts(dropna=False))
print(train[TARGET_COL].value_counts(normalize=True, dropna=False))

uniqueness_df = analyze_uniqueness(train)
uniqueness_df

=== Target distribution: COMP ONLY ===
Heart Disease
0    347546
1    282454
Name: count, dtype: int64
Heart Disease
0    0.55166
1    0.44834
Name: proportion, dtype: float64

=== Target distribution: EXTERNAL ONLY ===
Series([], Name: count, dtype: int64)
Series([], Name: proportion, dtype: float64)

=== Target distribution: MERGED (comp + external) ===
Heart Disease
0    347546
1    282454
Name: count, dtype: int64
Heart Disease
0    0.55166
1    0.44834
Name: proportion, dtype: float64

,Feature,Unique Values,Data Type,Heuristic Type,Mean,Std
14,is_external,1,int64,Categorical/Ordinal,0.000000,0.000000
1,Sex,2,int64,Categorical/Ordinal,0.714735,0.451541
8,Exercise angina,2,int64,Categorical/Ordinal,0.273725,0.445870
5,FBS over 120,2,int64,Categorical/Ordinal,0.079987,0.271274
13,Heart Disease,2,int64,Categorical/Ordinal,0.448340,0.497324
10,Slope of ST,3,int64,Categorical/Ordinal,1.455871,0.545192
6,EKG results,3,int64,Categorical/Ordinal,0.981660,0.998783
12,Thallium,3,int64,Categorical/Ordinal,4.618873,1.950007
2,Chest pain type,4,int64,Categorical/Ordinal,3.312752,0.851615
11,Number of vessels fluro,4,int64,Categorical/Ordinal,0.451040,0.798549
0,Age,42,int64,Continuous,54.136706,8.256301
3,BP,66,int64,Continuous,130.497433,14.975802
9,ST depression,66,float64,Continuous,0.716028,0.948472
7,Max HR,93,int64,Continuous,152.816763,19.112927
4,Cholesterol,150,int64,Continuous,245.011814,33.681581

In [16]:
numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()

skew_series = X[numeric_cols].skew().abs().sort_values(ascending=False)
top_skewed_features = skew_series.head(6).index.tolist()

print("Top 6 Most Skewed Features (Absolute Values):")
print(X[top_skewed_features].skew())

plt.figure(figsize=(16, 10))
for i, col in enumerate(top_skewed_features):
    plt.subplot(2, 3, i + 1)
    sns.histplot(X[col].sample(min(10000, len(X))), kde=True, color='teal', bins=30)
    plt.title(f"Feature: {col}\nSkewness: {X[col].skew():.2f}")
    plt.xlabel("")
    plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

Top 6 Most Skewed Features (Absolute Values):
Series([], dtype: float64)