In [1]:
import pandas as pd
import numpy as np

In [2]:
sub_1 = pd.read_csv('/kaggle/input/the-best-solo-model-so-far-realmlp-lb-0-95397/submission.csv')
sub_2 = pd.read_csv('/kaggle/input/heart-01/submission.csv')
sub_3 = pd.read_csv('/kaggle/input/notebooks/anthonytherrien/predicting-heart-disease-blend/submission.csv')
sub_4 = pd.read_csv('/kaggle/input/notebooks/harukiharada/realmlp-ext-target-stats-5-fold-cv/submission.csv')
sub_5 = pd.read_csv('/kaggle/input/notebooks/datasciencegrad/s6e2-catb-xgb-rf-res-k-fold-lb-0-95398/submission.csv')
sub_6 = pd.read_csv('/kaggle/input/notebooks/jacksaleeby/0-95398-rank-7-please-upvote-if-helpful/submission.csv')
sub_7 = pd.read_csv('/kaggle/input/notebooks/abhinavsharma0706/heart-02/submission.csv')

In [3]:
def percentile(x):
    return np.percentile(x, np.random.randint(10, 90))

In [4]:
df = pd.concat([sub_1.iloc[:, 1], sub_2.iloc[:, 1],
           sub_3.iloc[:, 1], 
                sub_4.iloc[:, 1],
               sub_5.iloc[:, 1],
               sub_6.iloc[:, 1],
               sub_7.iloc[:, 1]], axis=1)
          #  sub_5.iloc[:, 1], sub_6.iloc[:, 1],
          #  # sub_7.iloc[:, 1]
          # ], 
                # axis=1)
df

,Heart Disease,Heart Disease,Heart Disease,Heart Disease,Heart Disease,Heart Disease,Heart Disease
0,0.948185,0.948649,0.948203,0.944867,0.926765,0.947356,0.948649
1,0.011461,0.010849,0.010849,0.011438,0.019580,0.010849,0.010849
2,0.990032,0.990125,0.990035,0.989892,0.980204,0.989997,0.990125
3,0.006925,0.006479,0.006479,0.006932,0.009495,0.006479,0.006479
4,0.226334,0.224153,0.222306,0.214186,0.254060,0.221661,0.224153
...,...,...,...,...,...,...,...
269995,0.165329,0.163247,0.163247,0.164321,0.196653,0.163247,0.163247
269996,0.693318,0.692451,0.691707,0.672276,0.685308,0.687407,0.692451
269997,0.050569,0.050184,0.050184,0.050772,0.080107,0.050184,0.050184
269998,0.183966,0.184108,0.183971,0.174910,0.216060,0.181702,0.184108
269999,0.028665,0.028557,0.028473,0.028162,0.051438,0.028458,0.028557

In [ ]:
# import numpy as np
# import pandas as pd

# preds = df.copy()

# # convert each column to ranks
# ranked = np.apply_along_axis(lambda x: pd.Series(x).rank(method='average').to_numpy(), 0, preds)

# # average the ranks
# final_rank_avg = ranked.mean(axis=1)

# # optional: scale back to [0,1]
# final_pred = (final_rank_avg - final_rank_avg.min()) / (final_rank_avg.max() - final_rank_avg.min())

In [5]:
sam = pd.read_csv('/kaggle/input/playground-series-s6e2/sample_submission.csv')
# sam.iloc[:, -1] = (0.6*sub_1.iloc[:, -1] + 0.4*sub_2.iloc[:, -1])
# sam.iloc[:, -1] = df.median(axis=1)
# sam.iloc[:, -1] = final_pred

sam.iloc[:, -1] = df.apply(percentile, axis=1)
sam

/tmp/ipykernel_55/1979441599.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0         0.948212
1         0.011456
2         0.990125
3         0.006479
4         0.221829
            ...
269995    0.163247
269996    0.692332
269997    0.050610
269998    0.184086
269999    0.028637
Length: 270000, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  sam.iloc[:, -1] = df.apply(percentile, axis=1)

            id  Heart Disease
0       630000       0.948212
1       630001       0.011456
2       630002       0.990125
3       630003       0.006479
4       630004       0.221829
...        ...            ...
269995  899995       0.163247
269996  899996       0.692332
269997  899997       0.050610
269998  899998       0.184086
269999  899999       0.028637

[270000 rows x 2 columns]

In [6]:
sam.to_csv('submission.csv', index=False)